workflows:
  expo-managed-build:
    name: Expo Managed Workflow Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
      groups: []
      vars:
        # Expo access token, mark as secure in Codemagic
        EXPO_TOKEN: Encrypted
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing npm dependencies..."
          npm install --legacy-peer-deps
          npm install -g eas-cli
      - name: Build Android APK via EAS
        script: |
          echo "Starting EAS build for Android APK..."
          eas build -p android --profile production --apk --non-interactive
    artifacts:
      # Collect any artifacts if needed (EAS Cloud will provide download link)
      - build/**/*
