workflows:
  expo-managed-build:
    name: Expo Managed Workflow Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
      groups: []
      vars:
        EAS_TOKEN: Encrypted
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing npm dependencies with legacy peer deps..."
          npm install --legacy-peer-deps
      - name: Login to Expo
        script: |
          echo "Logging into Expo CLI..."
          npm install -g eas-cli
          eas login --token $EAS_TOKEN
      - name: Build Android APK via EAS
        script: |
          echo "Building Android APK via EAS..."
          eas build -p android --profile production --apk --non-interactive
    artifacts:
      - build/**/*
