workflows:
  expo-managed-build:
    name: Expo Managed Workflow Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
      groups:
        - default
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing npm dependencies..."
          # 先尝试使用 lockfile 安装，如果失败再 fallback
          (npm ci) || npm install --legacy-peer-deps

          # 补全 expo-router 依赖缺失的 ajv 模块
          npm install ajv@^8 ajv-keywords@^5 --save-dev

          # 确保 Expo 依赖版本正确
          npx expo install --fix --non-interactive

          # 安装 EAS CLI
          npm install -g eas-cli
      - name: Build Android APK via EAS
        script: |
          echo "Building Android APK via EAS..."
          eas build -p android --profile production --non-interactive
    artifacts:
      - build/**/*
