workflows:
  expo-managed-build:
    name: Expo Managed Workflow Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
      groups:
        - default
      vars:
        EXPO_TOKEN:  # 在后台设置真实 token 并加密
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing npm dependencies..."
          npm install --legacy-peer-deps
          npm install -g eas-cli
      - name: Build Android APK via EAS
        script: |
          echo "Building Android APK via EAS..."
          eas build -p android --profile production --apk --non-interactive
    artifacts:
      - build/**/*
